### ISSUE TITLE
Pail crashes jobs with a lot of Log::debug() output

### ISSUE THREAD

**Issue by cyppe** [laravel/pail#29]
### Laravel Package Version

1.1.0

### Laravel Version

10.41.0

### PHP Version

PHP 8.2.14 

### Description

I noticed an issue that if I terminate Pail (ctrl+c) when I have a Job running that sends a lot of logs to Log::debug() so basically Laravel Pail is lagging behind vs how fast the logs comes in laravel.log if I also tail it in the same time I can see that Pail probably is 10 seconds behind the realtime logs.

So basically I terminate Pail (ctrl+c) and as I also tail -f storage/laravel.log I see instantly that my job is killed with exception:

```
[2024-01-24 11:00:40] local.ERROR: Job failed on attempt 2 due to: **filemtime(): stat failed** for /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/storage/pail/**65b0ed6061aa6.pail**
[2024-01-24 11:00:40] local.ERROR: filemtime(): stat failed for /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/storage/pail/65b0ed6061aa6.pail {"exception":"[object] (ErrorException(code: 0): filemtime(): stat failed for /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/storage/pail/65b0ed6061aa6.pail at /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/pail/src/File.php:90)
```

**Full output including a few lines from Log::debug() logs:**

```

[2024-01-24 11:00:39] local.DEBUG: Chunk: 193 - Before addProduct - Current Memory Usage: 964 MB
[2024-01-24 11:00:39] local.DEBUG: Chunk: 193 - finished addProduct - Current Memory Usage: 964 MB
[2024-01-24 11:00:39] local.DEBUG: Chunk: 193 - Before mapRedisCacheProductToEsales - Current Memory Usage: 964 MB
[2024-01-24 11:00:39] local.DEBUG: Chunk: 193 - Before addProduct - Current Memory Usage: 964 MB
[2024-01-24 11:00:40] local.DEBUG: Chunk: 193 - finished addProduct - Current Memory Usage: 964 MB
[2024-01-24 11:00:40] local.DEBUG: Chunk: 193 - Before mapRedisCacheProductToEsales - Current Memory Usage: 964 MB
[2024-01-24 11:00:40] local.DEBUG: Chunk: 193 - Before addProduct - Current Memory Usage: 964 MB
[2024-01-24 11:00:40] local.DEBUG: Chunk: 193 - finished addProduct - Current Memory Usage: 964 MB
[2024-01-24 11:00:40] local.DEBUG: Chunk: 193 - Before mapRedisCacheProductToEsales - Current Memory Usage: 964 MB
[2024-01-24 11:00:40] local.DEBUG: Chunk: 193 - Before addProduct - Current Memory Usage: 964 MB
[2024-01-24 11:00:40] local.DEBUG: Chunk: 193 - finished addProduct - Current Memory Usage: 964 MB
[2024-01-24 11:00:40] local.ERROR: Job failed on attempt 2 due to: filemtime(): stat failed for /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/storage/pail/65b0ed6061aa6.pail
[2024-01-24 11:00:40] local.ERROR: filemtime(): stat failed for /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/storage/pail/65b0ed6061aa6.pail {"exception":"[object] (ErrorException(code: 0): filemtime(): stat failed for /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/storage/pail/65b0ed6061aa6.pail at /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/pail/src/File.php:90)
[stacktrace]
#0 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'filemtime(): st...', '/Users/thomasan...', 90)
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'filemtime(): st...', '/Users/thomasan...', 90)
#2 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/pail/src/File.php(90): filemtime('/Users/thomasan...')
#3 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/pail/src/File.php(64): Laravel\\Pail\\File->isStale()
#4 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/pail/src/Handler.php(49): Laravel\\Pail\\File->log('debug', 'Chunk: 193 - fi...', Array)
#5 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Laravel\\Pail\\Handler->Laravel\\Pail\\{closure}(Object(Laravel\\Pail\\File), 1)
#6 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/pail/src/Handler.php(48): Illuminate\\Support\\Collection->each(Object(Closure))
#7 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/pail/src/PailServiceProvider.php(48): Laravel\\Pail\\Handler->log(Object(Illuminate\\Log\\Events\\MessageLogged))
#8 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(458): Laravel\\Pail\\PailServiceProvider->Laravel\\Pail\\{closure}(Object(Illuminate\\Log\\Events\\MessageLogged))
#9 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Log\\\\...', Array)
#10 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Log\\\\...', Array, false)
#11 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Log/Logger.php(248): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Log\\\\...')
#12 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Log/Logger.php(189): Illuminate\\Log\\Logger->fireLogEvent('debug', 'Chunk: 193 - fi...', Array)
#13 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Log/Logger.php(145): Illuminate\\Log\\Logger->writeLog('debug', 'Chunk: 193 - fi...', Array)
#14 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(734): Illuminate\\Log\\Logger->debug('Chunk: 193 - fi...', Array)
#15 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Log\\LogManager->debug('Chunk: 193 - fi...')
#16 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/app/Jobs/ImportProductsToEsalesJob.php(152): Illuminate\\Support\\Facades\\Facade::__callStatic('debug', Array)
#17 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\ImportProductsToEsalesJob->handle()
#18 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#20 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#21 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#22 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#23 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\ImportProductsToEsalesJob))
#24 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ImportProductsToEsalesJob))
#25 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#26 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\ImportProductsToEsalesJob), false)
#27 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\ImportProductsToEsalesJob))
#28 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/app/Jobs/Middleware/CustomWithoutOverlapping.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ImportProductsToEsalesJob))
#29 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Jobs\\Middleware\\CustomWithoutOverlapping->handle(Object(App\\Jobs\\ImportProductsToEsalesJob), Object(Closure))
#30 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ImportProductsToEsalesJob))
#31 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(App\\Jobs\\ImportProductsToEsalesJob))
#33 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#34 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#35 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#36 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#37 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon('redis', 'esales', Object(Illuminate\\Queue\\WorkerOptions))
#38 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'esales')
#39 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#40 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#41 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#42 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#43 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#44 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#45 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call(Array)
#46 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#47 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#48 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#50 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#52 /Users/thomasandersson/PhpstormProjects/motoaction_new_generate/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#53 {main}
"}


```

### Steps To Reproduce

1. Create a job that sends a LOT of Log::debug("Something");  Potentially need to catch exception and send to log.
2. Have laravel pail running
3. Dispatch job and look at the flood of logs in laravel pail.
4. Terminate Pail with ctrl+c 
5.  Look at laravel logs and see that job died due to exception described above (filemtime(): stat failed for /...../storage/pail/65b0ed6061aa6.pail)

**Comment by driesvints** [comment]
Yeah this look like it needs a file exists check. I'm not sure if we need to log it if it doesn't exists. Could you send in a PR and we can work from there?

**Comment by cyppe** [comment]
The problem is that the file does exist as it did not go into the block of if (!$this->exists()) { .. }, so it's something else going on. I read a discussion here that sometimes the file can be removed so fast that it exists on file_exists check and then it's gone with filemtime runs.  I will make a PR that checks if file exists first but also supress the error with @ just in case.

The problem is that I don't 100% understand the use case of isStale, so I don't know what the correct fallback behavior is. If it's better it returns true or false if we cannot receive filemtime so I need some help there.

https://github.com/yiisoft/yii2/issues/17556

And yes - logging is not needed. It was just my attempt to see if it did go into the the blocks.
